name: Main Pipeline

on:
  push:
    branches: [ main ]
    
env:
  VERSION: 3.0.0.0-alpha1

jobs:
  build:
    
    name: Test ${{ matrix.project }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    env:
      NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        project:
          - Wabbajack.DTOs.Test
          - Wabbajack.Hashing.xxHash64.Test
          - Wabbajack.Networking.Http.Test
          - Wabbajack.Networking.NexusApi.Test
          - Wabbajack.Paths.Test
          - Wabbajack.Paths.IO.Test

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          
      - name: Install dependencies
        run: dotnet restore ${{ matrix.project }}/${{ matrix.project }}.csproj
      - name: Build
        run: dotnet build ${{ matrix.project }}/${{ matrix.project }}.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test ${{ matrix.project }}/${{ matrix.project }}.csproj --no-restore --verbosity normal
        
  publish:
    name: Publish ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - Wabbajack.Downloaders.Interfaces
          - Wabbajack.DTOs
          - Wabbajack.Hashing.xxHash64
          - Wabbajack.Networking.Http
          - Wabbajack.Networking.Http.Interfaces
          - Wabbajack.Networking.NexusApi
          - Wabbajack.Paths
          - Wabbajack.Paths.IO
          
    needs: build
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true      

      - name: Publish ${{ matrix.project}} NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: ${{ matrix.project }}/${{ matrix.project }}.csproj
          VERSION_STATIC: ${{ env.VERSION }}
          NUGET_KEY: ${{secrets.NUGET_KEY}}
    